import { test, expect } from "bun:test";
import { normalizeVars, nvimTheme, tmuxTheme, SNIPPETS } from "../src/themesync.ts";

const VARS = {
  "--bg": "#0f0a1a", "--bg2": "#1a1333", "--bg3": "#2d1b4e",
  "--text": "#f3e8ff", "--text2": "#e9d5ff", "--text3": "#d8b4fe",
  "--border": "#6d28d9", "--primary": "#a78bfa", "--primary-hover": "#c4b5fd",
  "--success": "#34d399", "--warning": "#fbbf24", "--error": "#f472b6", "--info": "#a78bfa",
};

test("reads the CSS custom-property names the app actually uses", () => {
  const v = normalizeVars(VARS);
  expect(v.bg).toBe("#0f0a1a");
  expect(v.primaryHover).toBe("#c4b5fd");
});

test("accepts the same keys without the leading dashes", () => {
  expect(normalizeVars({ bg: "#123456" }).bg).toBe("#123456");
});

// These strings are written into a file a shell sources and another a Lua
// interpreter runs. Anything that isn't a colour must never reach them.
test("rejects non-hex values and falls back", () => {
  const v = normalizeVars({ "--bg": "red; rm -rf /", "--primary": "$(whoami)" });
  expect(v.bg).toBe("#0d1117");
  expect(v.primary).toBe("#a78bfa");
});

test("rejects CSS colour functions, which are valid CSS but not colours here", () => {
  expect(normalizeVars({ "--bg": "color-mix(in srgb, red, blue)" }).bg).toBe("#0d1117");
  expect(normalizeVars({ "--bg": "rgba(0,0,0,0.8)" }).bg).toBe("#0d1117");
});

test("accepts the short and alpha hex forms", () => {
  expect(normalizeVars({ "--bg": "#abc" }).bg).toBe("#abc");
  expect(normalizeVars({ "--bg": "#11223344" }).bg).toBe("#11223344");
});

test("the nvim file is a module that applies itself", () => {
  const out = nvimTheme(normalizeVars(VARS), "Midnight Purple");
  expect(out).toContain("return M");
  expect(out).toContain("function M.apply()");
  // Without the autocmd a colorscheme loaded later in startup paints over it.
  expect(out).toContain('nvim_create_autocmd("ColorScheme"');
  expect(out).toContain("#0f0a1a");
});

test("syntax is themed by role, so every palette reads as itself", () => {
  const out = nvimTheme(normalizeVars(VARS), "x");
  // Chrome-only theming made every palette look like "dark" or "light" — the
  // background moved and nothing else did.
  for (const g of ["String", "Comment", "Function", "Keyword", "Type"]) {
    expect(out).toContain(`"${g}"`);
  }
  // Roles, not hues: the accent carries keywords and success carries strings,
  // which is what makes the mapping hold across all of them.
  expect(out).toContain(`hl("Keyword", { fg = "${VARS["--primary"]}" })`);
  expect(out).toContain(`hl("String", { fg = "${VARS["--success"]}" })`);
});

test("the tab strip is flush with the terminal background", () => {
  const out = nvimTheme(normalizeVars(VARS), "x");
  // A slab of a slightly-different grey across the top is the seam that gives
  // away that the editor is embedded in something else.
  expect(out).toContain(`hl("TabLineFill", { bg = "${VARS["--bg"]}" })`);
  expect(out).toContain(`hl("BufferLineFill", { bg = "${VARS["--bg"]}" })`);
});

test("the tmux status bar is flush too, not a panel-coloured slab", () => {
  const out = tmuxTheme(normalizeVars(VARS), "x");
  expect(out).toContain(`set -g status-style "bg=${VARS["--bg"]}`);
  expect(out).toContain(`setw -g window-status-current-style "bg=${VARS["--bg2"]},fg=${VARS["--primary"]}`);
});

test("the tmux file sets chrome and is safe to source twice", () => {
  const out = tmuxTheme(normalizeVars(VARS), "x");
  expect(out).toContain("status-style");
  expect(out).toContain("pane-active-border-style");
  // Every line is an idempotent `set`; nothing appends or toggles.
  for (const line of out.split("\n")) {
    const t = line.trim();
    if (!t || t.startsWith("#")) continue;
    expect(t.startsWith("set ") || t.startsWith("setw ")).toBe(true);
  }
});

test("both files say they are generated, so nobody hand-edits them", () => {
  const v = normalizeVars(VARS);
  expect(nvimTheme(v, "x")).toContain("Generated by agentglass");
  expect(tmuxTheme(v, "x")).toContain("Generated by agentglass");
});

test("the opt-in snippets point at the files we actually write", () => {
  expect(SNIPPETS.nvim).toContain("agentglass/theme.lua");
  expect(SNIPPETS.tmux).toContain("agentglass/theme.tmux.conf");
  // `-q` so a tmux started before agentglass ever ran doesn't error on a
  // missing file.
  expect(SNIPPETS.tmux).toContain("-q");
});
