// The QR encoder, pinned against outside authorities rather than against
// itself.
//
// Three layers, because "it produced a picture" is not a test:
//   * the Reed-Solomon step is checked against the published worked example
//     for "HELLO WORLD" at version 1-M, so the finite-field maths cannot drift;
//   * the finished symbol is compared module-for-module with a fixture that was
//     generated by libqrencode (`qrencode -8 -l M`) and confirmed identical, so
//     a regression in placement, masking or format bits shows up as a diff;
//   * the structural invariants a scanner looks for are asserted directly.
//
// Every case in the fixture was additionally rendered and read back with zbar
// during development, which is the only check that really matters: a code that
// decodes to exactly what went in.
import { describe, expect, test } from "bun:test";
import { qrMatrix, qrSvgPath, ecCodewords, formatBits, versionBits, penalty } from "../src/lib/qr.ts";

const URL_CASE = "http://192.168.1.131:4010/?token=tu7ynwt63m";

/** Generated by our encoder and verified identical to `qrencode -8 -l M -t ASCII`. */
const FIXTURE = [
  "#######.##.#.####...#.###.#######",
  "#.....#...##.##.#.###...#.#.....#",
  "#.###.#..#....#..###.#..#.#.###.#",
  "#.###.#.#.##....##.#.###..#.###.#",
  "#.###.#.#.##....#..#.##...#.###.#",
  "#.....#.###...##....#..##.#.....#",
  "#######.#.#.#.#.#.#.#.#.#.#######",
  "........#.#...#..#.####.#........",
  "#...#.###.###..#.##..#.#.#####..#",
  ".#.....####.#.####..##.##....##..",
  "..#######..######.#.#..###...#.#.",
  "##..#...##...#.#......##.##....#.",
  ".#..###.#....#..#..#..#.#.####...",
  "###..#.#..#.#.#...####..#..#.##..",
  "#...###....##..#.#..#..##..#.#.#.",
  "##.##...##.##..###...#####.......",
  "....#####..##...####.#.#.##.##.#.",
  "##..#..##.#######...#.###....##..",
  "###.####.#.#.#.#.#..####.#...#...",
  "........##.####..###.#..#.......#",
  ".###.######..###..###..####.##...",
  "##.###.#####.##.#..#..##...#.###.",
  "..##.####.##.##.##.#.####.#.#..#.",
  "..#.##.#.#.#.#...#####...#.#.#.##",
  "##..###.#....#.####..#..######.#.",
  "........#...#..#.#..##..#...#.##.",
  "#######.##.#...#..#.#...#.#.##.#.",
  "#.....#......#........###...##.#.",
  "#.###.#.#.#....##..#..#.######..#",
  "#.###.#...##.##...####...##.####.",
  "#.###.#..#..#.##.#..#..#.####.#..",
  "#.....#..#.##..###...##.##.#.....",
  "#######.##.#.....###.#..##..##..#",
];

const render = (m: boolean[][]): string[] => m.map((row) => row.map((v) => (v ? "#" : ".")).join(""));

describe("reed-solomon", () => {
  test("matches the published HELLO WORLD vector (version 1-M)", () => {
    const data = [32, 91, 11, 120, 209, 114, 220, 77, 67, 64, 236, 17, 236, 17, 236, 17];
    expect(ecCodewords(data, 10)).toEqual([196, 35, 39, 119, 235, 215, 231, 226, 93, 23]);
  });

  test("EC codeword count is what was asked for", () => {
    for (const n of [10, 16, 18, 22, 24, 26]) expect(ecCodewords([1, 2, 3], n)).toHaveLength(n);
  });
});

describe("format and version information", () => {
  // The eight format strings for EC level M are fixed by the spec; getting one
  // wrong makes a symbol that looks right and scans as nothing.
  test("format bits are the spec's values for level M", () => {
    expect([0, 1, 2, 3, 4, 5, 6, 7].map(formatBits)).toEqual([
      0x5412, 0x5125, 0x5e7c, 0x5b4b, 0x45f9, 0x40ce, 0x4f97, 0x4aa0,
    ]);
  });

  test("version bits are the spec's values where they exist (7 and up)", () => {
    expect(versionBits(7)).toBe(0x07c94);
    expect(versionBits(8)).toBe(0x085bc);
    expect(versionBits(9)).toBe(0x09a99);
  });
});

describe("qrMatrix", () => {
  test("reproduces the libqrencode fixture exactly", () => {
    expect(render(qrMatrix(URL_CASE))).toEqual(FIXTURE);
  });

  test("picks the smallest version that fits, and grows with the payload", () => {
    expect(qrMatrix("x").length).toBe(21); // version 1
    expect(qrMatrix("a".repeat(40)).length).toBe(29); // version 3
    expect(qrMatrix("a".repeat(120)).length).toBe(45); // version 7
  });

  test("refuses a payload past version 9 rather than truncating it", () => {
    // A code that encodes half a token would still scan, which is worse than
    // no code at all.
    expect(() => qrMatrix("a".repeat(200))).toThrow(/version 9/);
  });

  test("carries the three finder patterns and their separators", () => {
    const m = qrMatrix(URL_CASE);
    const size = m.length;
    for (const [r0, c0] of [[0, 0], [0, size - 7], [size - 7, 0]] as [number, number][]) {
      expect(m[r0]![c0]).toBe(true);
      expect(m[r0 + 1]![c0 + 1]).toBe(false); // the light ring
      expect(m[r0 + 3]![c0 + 3]).toBe(true); // the 3x3 core
    }
  });

  test("timing patterns alternate along row and column 6", () => {
    const m = qrMatrix(URL_CASE);
    for (let i = 8; i < m.length - 8; i++) {
      expect(m[6]![i]).toBe(i % 2 === 0);
      expect(m[i]![6]).toBe(i % 2 === 0);
    }
  });

  test("the dark module is set", () => {
    const m = qrMatrix(URL_CASE);
    expect(m[m.length - 8]![8]).toBe(true);
  });

  test("a forced mask still produces a well-formed symbol", () => {
    // Any of the eight masks is a valid code; only the heuristic differs. This
    // pins that forcing one changes the data area and nothing structural.
    for (let mask = 0; mask < 8; mask++) {
      const m = qrMatrix(URL_CASE, mask);
      expect(m.length).toBe(33);
      expect(m[m.length - 8]![8]).toBe(true);
      expect(m[6]![8]).toBe(true);
    }
    expect(render(qrMatrix(URL_CASE, 0))).not.toEqual(render(qrMatrix(URL_CASE, 1)));
  });

  test("the chosen mask is the lowest-penalty one", () => {
    const scores = Array.from({ length: 8 }, (_, mask) => penalty(qrMatrix(URL_CASE, mask)));
    const best = scores.indexOf(Math.min(...scores));
    expect(render(qrMatrix(URL_CASE))).toEqual(render(qrMatrix(URL_CASE, best)));
  });

  test("penalises a blank field heavily — it is all one colour", () => {
    const blank = Array.from({ length: 21 }, () => new Array(21).fill(false));
    expect(penalty(blank)).toBeGreaterThan(500);
  });
});

describe("qrSvgPath", () => {
  test("draws one unit square per dark module", () => {
    const m = qrMatrix(URL_CASE);
    const dark = m.flat().filter(Boolean).length;
    expect(qrSvgPath(m).match(/M/g)!.length).toBe(dark);
  });

  test("is empty for a matrix with nothing dark", () => {
    expect(qrSvgPath([[false, false], [false, false]])).toBe("");
  });
});
